/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alex' at '14.11.16 15:07' with Gradle 2.13
 *
 * @author alex, @date 14.11.16 15:07
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
